---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
     - name: Remove ELB with below given name
       ec2_elb_lb:
        name: "test-please-delete"
        state: absent
        region: us-east-2
        wait: yes
