---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
    - name: ec2 Termination
      ec2:
        region: us-east-2
        instance_ids: i-02f14078ad13918cd
        state: absent
