---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
    - name: Remove snapshot with below given name
      ec2_snapshot:
          region: us-east-2
          snapshot_id: snap-05e1905fc1fd6053f 
          state: absent

