---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
    - name: Remove AMI with below given name
      ec2_ami:
         image_id: ami-066a7f2e4b2d89a68
         delete_snapshot: yes
         state: absent

