---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
    - name: Create New AMI with below given name
      ec2_ami:
        instance_id: i-04bf630bc0b393cd3
        wait: yes
        name: newtest
        tags:
           Name: newtest
