---
  - hosts: localhost
    connection: local
    gather_facts: False
    tasks:
        - name: Create multiple directories
          file: path={{item}} state=absent
          with_items:
             - '/home/test1'
             - '/home/test2'
             - '/home/test3'
